include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types: true
    - always_use_package_imports: true
    - prefer_const_constructors: false
    - prefer_single_quotes: true
    - always_specify_types: false
    - avoid_print: true
    - sort_child_properties_last: true
    - await_only_futures: true
    - require_trailing_commas: true
    - use_build_context_synchronously: false
    - valid_regexps: true
    - unawaited_futures: false


analyzer:
  exclude: [build/**]



