include:
  - package:flutter_lints/flutter.yaml
  - package:lints/core.yaml


linter:

  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    prefer_const_constructors: false
    prefer_single_quotes: true
    always_specify_types: true
    avoid_print: true
    sort_child_properties_last: true
    await_only_futures: true
    require_trailing_commas: true
    use_build_context_synchronously: false


analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-raw-types: true

