include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types: true
    - always_specify_types: true
    - always_use_package_imports: true
    - avoid_empty_else: true
    - avoid_init_to_null: true
    - avoid_nullable_to_string_in_string_interpolation: true
    - avoid_print: true
    - avoid_redundant_argument_values: true
    - avoid_returning_null_for_future: true
    - avoid_unnecessary_containers: true
    - avoid_renaming_method_parameters: true
    - await_only_futures: true
    - camel_case_types: true
    - prefer_const_literals_to_create_immutables: true
    - prefer_final_parameters: true
    - prefer_int_literals: true
    - prefer_is_empty: true
    - prefer_null_aware_operators: true
    - prefer_single_quotes: true
    - prefer_spread_collections: true
    - public_member_api_docs: true
    - require_trailing_commas: true
    - sort_child_properties_last: true
    - unawaited_futures: false
    - unnecessary_const: true
    - unnecessary_new: true
    - use_build_context_synchronously: true
    - use_key_in_widget_constructors: true
    - valid_regexps: true

analyzer:
  exclude: [build/**]
