name: whatsevr_app
description: "Whatsevr is a Social Media Frontend similar to linkedin"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  equatable: ^2.0.5
  gap: ^3.0.1
  extended_image: ^8.2.1
  carousel_slider: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animated_hint_textfield: ^1.0.3
  timeago: ^3.7.0
  flutter_smart_dialog: ^4.9.8
  rotated_corner_decoration: ^2.1.0+1
  google_fonts: ^6.2.1
  share_plus: ^10.0.2
  intl: ^0.19.0
  waterfall_flow: ^3.0.3
  flutter_staggered_grid_view: ^0.7.0
  animated_read_more_text: ^0.0.6
  file_picker: ^8.1.2
  flutter_native_splash: any
  dio: ^5.6.0
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  path_provider: ^2.1.4
  iconify_flutter: ^0.0.5
  video_player: ^2.9.1
  wakelock_plus: ^1.2.8
  smooth_page_indicator: ^1.2.0+3
  chewie: ^1.8.3
  like_button: ^2.0.5
  otpless_flutter: ^2.1.7
  skeletonizer: ^1.4.2
  detectable_text_field: ^3.0.2
  supabase: ^2.3.0
  easy_refresh: ^3.4.0
  collection: ^1.18.0
  video_thumbnail: ^0.5.3
  shorebird_code_push: ^1.1.4
  background_downloader: ^8.5.5
  permission_handler: ^11.3.1
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  image_picker: ^1.1.2
  flutter_svg: any



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
# dart run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/whatsevr_app_logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - shorebird.yaml

