name: whatsevr_app
description: "Whatsevr is a Social Media Frontend similar to linkedin"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  rxdart: any
  equatable: ^2.0.5
  gap: ^3.0.1
  extended_image: ^8.3.1
  carousel_slider: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animated_hint_textfield: ^1.0.3
  get_time_ago: ^2.0.0
  flutter_smart_dialog: ^4.9.8+2
  rotated_corner_decoration: ^2.1.0+1
  google_fonts: ^6.2.1
  share_plus: ^10.0.2
  intl: any
  waterfall_flow: ^3.0.3
  flutter_staggered_grid_view: ^0.7.0
  animated_read_more_text: ^0.0.6
  file_picker: ^8.1.2
  flutter_native_splash: any
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  path_provider: ^2.1.4
  iconify_flutter: ^0.0.5
  cached_video_player_plus: ^3.0.3
#  better_player: ^0.0.84
  wakelock_plus: ^1.2.8
  smooth_page_indicator: ^1.2.0+3

  like_button: ^2.0.5
  otpless_flutter: ^2.2.1
  skeletonizer: ^1.4.2
  detectable_text_field: ^3.0.2
  supabase: ^2.4.0
  cloudinary: ^1.2.0
  easy_refresh: ^3.4.0
  collection: any
  video_thumbnail: ^0.5.3
  shorebird_code_push: ^1.1.6
  background_downloader: ^8.5.6
  permission_handler: ^11.3.1
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  image_picker: ^1.1.2
  flutter_svg: any
  wechat_assets_picker: ^9.3.3
  camera: ^0.11.0+2
  pro_image_editor: ^5.4.2
  crop_your_image: ^1.1.0
  video_trimmer: ^3.0.1
  video_editor: ^3.0.0
  ffmpeg_kit_flutter: ^6.0.3
  fraction: ^5.0.3
  firebase_core: any
  firebase_crashlytics: any
  firebase_analytics: any
  firebase_messaging: any
  geobase: ^1.3.0
  geolocator: ^13.0.1 #current location gapi
  geocoding: ^3.0.0 #place name to lat long for wkb without gapi
  easy_debounce: ^2.0.3
  hidable: ^1.0.6
  media_info: ^0.12.0+2
  flutter_foreground_task: ^8.10.2
  double_back_to_exit: ^1.1.0
  awesome_notifications_core: ^0.10.0
  awesome_notifications: any
  visibility_detector: ^0.4.0+2
  preload_page_view: ^0.2.0
  expansion_tile_group: ^2.1.0
  story_view_advance: ^0.2.0
  flutter_custom_tabs: ^2.1.0
  flutter_link_previewer: ^3.2.2
  animate_do: ^3.3.4
  markdown_editor_plus: ^0.2.15
  country_state_city_pro: ^0.0.6
  flutter_cached_pdfview: ^0.4.2
  flutter_advanced_avatar: ^1.5.0
  screen_brightness: ^2.0.0+2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
#dart run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: assets/images/whatsevr_app_logo.jpg

flutter_native_splash:
#dart run flutter_native_splash:create
  color: "#ffffff"
  image: assets/images/whatsevr_app_logo.jpg
  android: true
  android_12:
    image: assets/images/whatsevr_app_logo.jpg
    color: "#ffffff"
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - shorebird.yaml

