name: whatsevr_app
description: "Whatsevr is a Social Media Frontend similar to linkedin"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  animated_hint_textfield: ^1.0.3
  animated_read_more_text: ^0.0.6
  animated_toast_list: ^1.0.2
  awesome_notifications: any
  awesome_notifications_core: ^0.10.0
  background_downloader: ^8.6.0
  bloc: ^8.1.4
  cached_video_player_plus: ^3.0.3
  camera: ^0.11.0+2
  carousel_slider: ^5.0.0
  cloudinary: ^1.2.0
  collection: any
  country_state_city_pro: ^0.0.6
  crop_your_image: ^1.1.0

  cupertino_icons: ^1.0.8
  detectable_text_field: ^3.0.2
  device_region: ^1.4.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^4.0.0
  dio_smart_retry: ^6.0.0
  double_back_to_exit: ^1.1.0
  easy_debounce: ^2.0.3
  easy_refresh: ^3.4.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  expansion_tile_group: ^2.1.0
  extended_image: ^9.0.7
  ffmpeg_kit_flutter: ^6.0.3
  file_picker: ^8.1.4
  firebase_analytics: any
  firebase_core: any
  firebase_crashlytics: any
  firebase_messaging: any
  flutter:
    sdk: flutter
  flutter_advanced_avatar: ^1.5.0
  flutter_bloc: ^8.1.6
  flutter_cached_pdfview: ^0.4.3
  flutter_custom_tabs: ^2.1.0
  flutter_foreground_task: ^8.13.0
  flutter_image_compress: ^2.3.0
  flutter_link_previewer: ^3.2.2
  flutter_smart_dialog: ^4.9.8+5
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: any
  fluttertagger: ^2.2.1
  fraction: ^5.0.3
  gap: ^3.0.1
  geobase: ^1.3.0
  geocoding: ^3.0.0 #place name to lat long for wkb without gapi
  geolocator: ^13.0.1 #current location gapi
  get_time_ago: ^2.0.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  hidable: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.5
  iconify_flutter: ^0.0.7
  image_picker: ^1.1.2
  intl: any
  like_button: ^2.0.5
  markdown_editor_plus: ^0.2.15
  media_info: ^0.12.0+2
  otpless_flutter: ^2.2.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  preload_page_view: ^0.2.0
  pro_image_editor: ^5.4.2
  rotated_corner_decoration: ^2.1.0+1
  rxdart: any
  screen_brightness: ^2.0.0+2
  share_plus: ^10.0.2
  shorebird_code_push: ^2.0.2
  skeletonizer: ^1.4.2
  smooth_page_indicator: ^1.2.0+3
  story_view_advance: ^0.2.0
  supabase: ^2.5.0
  supabase_flutter: ^2.8.0
  talker_bloc_logger: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  username_generator:
    git:
      url: https://github.com/whatsevr/username_generator.dart.git
  video_editor: ^3.0.0
  video_thumbnail: ^0.5.3
  video_trimmer: ^3.0.1
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.8
  waterfall_flow: ^3.0.3
  wechat_assets_picker: ^9.4.1

dependency_overrides:
  file_picker:
    git:
      url: https://github.com/abdelaziz-mahdy/flutter_file_picker
      ref: fix-flutter-3.27-compile-error
      
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

# dart run icons_launcher:create
icons_launcher:
  image_path: 'assets\images\app_icon_transparent.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - shorebird.yaml
  fonts:
    - family: whatsevr-icon
      fonts:
        - asset: assets/icons/whatsevr-icon.ttf
