name: whatsevr_app
description: "A new whatsevr project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  gap: ^3.0.1
  extended_image: ^8.2.0
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animated_hint_textfield: ^1.0.1
  timeago: ^3.6.1
  flutter_smart_dialog: ^4.9.6
  rotated_corner_decoration: ^2.1.0+1
  google_fonts: ^6.1.0
  share_plus: ^7.2.2
  intl: ^0.19.0
  waterfall_flow: ^3.0.3
  animated_read_more_text: ^0.0.6
  file_picker: ^6.2.0
  flutter_native_splash: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

